// const element = document.getElementById('selectme')
// const element = document.getElementsByClassName('heading')
// const element = document.getElementsByTagName('h2')
const element = document.querySelector('h3.heading')
console.log(element)